name: Build MAUI iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build MAUI iOS
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI
        run: dotnet workload install maui

      - name: Show Environment
        run: |
          dotnet --version
          dotnet --info
          dotnet workload list
          xcodebuild -version

      - name: Restore
        run: dotnet restore MauiApp3/MauiApp3.csproj

      - name: Build iOS
        run: |
          dotnet publish MauiApp3/MauiApp3.csproj \
            -f net9.0-ios \
            -c Release \
            -p:ArchiveOnBuild=true \
            -p:RuntimeIdentifier=ios-arm64

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: MauiApp3-iOS
          path: |
            MauiApp3/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa
          retention-days: 7
